<?php
if (!defined('IN_CRONLITE')) exit();
$paytype = $DB->getAll("SELECT * FROM pre_type WHERE status=1 ORDER BY id ASC");
?>
<div id="toc2" class="api_block">
  <h3>
    协议规则
  </h3>
  <p>传输方式：HTTP</p>
  <p>数据格式：JSON</p>
  <p>签名算法：MD5</p>
  <p>字符编码：UTF-8</p>
</div>
<div id="pay0" class="api_block">
  <h3>
    页面跳转支付
  </h3>
  <p>
    <font color="#777">此接口可用于用户前台直接发起支付，使用form表单跳转或拼接成url跳转。</font>
  </p>
  <p>URL地址：<font color="#29389f">http://payapi.dx888.me/submit.php</font>
  </p>
  <p>POST数据：<font color="#29389f">pid={商户ID}&amp;type={支付方式}&amp;out_trade_no={商户订单号}&amp;notify_url={服务器异步通知地址}&amp;name={商品名称}&amp;money={金额}&amp;sign={签名字符串}&amp;sign_type=MD5</font>
  </p>
  <p>请求参数说明：</p>
  <table class="table table-bordered table-hover">
    <thead>
      <tr>
        <th>字段名</th>
        <th>变量名</th>
        <th>必填</th>
        <th>类型</th>
        <th>示例值</th>
        <th>描述</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>商户ID</td>
        <td>pid</td>
        <td>是</td>
        <td>Int</td>
        <td>1001</td>
        <td></td>
      </tr>
      <tr>
        <td>支付方式</td>
        <td>type</td>
        <td>是</td>
        <td>String</td>
        <td>charge</td>
        <td><a href="#pay7" style="color:#4585d2">支付方式列表</a></td>
      </tr>
      <tr>
        <td>商户订单号</td>
        <td>out_trade_no</td>
        <td>是</td>
        <td>String</td>
        <td>20160806151343349</td>
        <td>格式：a-zA-Z0-9，长度6-32位</td>
      </tr>
      <tr>
        <td>异步通知地址</td>
        <td>notify_url</td>
        <td>是</td>
        <td>String</td>
        <td>http://www.pay.com/notify_url.php</td>
        <td>服务器异步通知地址，以 http:// 或 https:// 开头</td>
      </tr>
      <tr>
        <td>商品名称</td>
        <td>name</td>
        <td>是</td>
        <td>String</td>
        <td>VIP会员</td>
        <td></td>
      </tr>
      <tr>
        <td>商品金额</td>
        <td>money</td>
        <td>是</td>
        <td>String</td>
        <td>100</td>
        <td>整型数值，不能有小数点</td>
      </tr>
      <tr>
        <td>业务扩展参数</td>
        <td>param</td>
        <td>否</td>
        <td>String</td>
        <td>没有请留空</td>
        <td></td>
      </tr>
      <tr>
        <td>签名字符串</td>
        <td>sign</td>
        <td>是</td>
        <td>String</td>
        <td>202cb962ac59075b964b07152d234b70</td>
        <td></td>
      </tr>
      <tr>
        <td>签名类型</td>
        <td>sign_type</td>
        <td>是</td>
        <td>String</td>
        <td>MD5</td>
        <td>默认为MD5</td>
      </tr>
      <tr>
        <td>语言</td>
        <td>lang</td>
        <td>否</td>
        <td>String</td>
        <td>chinese_hongkong</td>
        <td>chinese_hongkong, chinese_simple, english<br />默认为 chinese_hongkong</td>
      </tr>
    </tbody>
  </table>
</div>
<div id="pay1" class="api_block">
  <h3>
    支付结果通知
  </h3>
  <p>通知类型：服务器异步通知（notify_url）</p>
  <p>请求方式：POST，数据以json的形式放在请求的body中。</p>
  <p>请求参数说明：</p>
  <table class="table table-bordered table-hover">
    <thead>
      <tr>
        <th>字段名</th>
        <th>变量名</th>
        <th>必填</th>
        <th>类型</th>
        <th>示例值</th>
        <th>描述</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>商户ID</td>
        <td>pid</td>
        <td>是</td>
        <td>Int</td>
        <td>1001</td>
        <td></td>
      </tr>
      <tr>
        <td>平台订单号</td>
        <td>trade_no</td>
        <td>是</td>
        <td>String</td>
        <td>20160806151343349021</td>
        <td><?php echo $conf['sitename'] ?>订单号</td>
      </tr>
      <tr>
        <td>商户订单号</td>
        <td>out_trade_no</td>
        <td>是</td>
        <td>String</td>
        <td>20160806151343349</td>
        <td>商户系统内部的订单号</td>
      </tr>
      <tr>
        <td>支付方式</td>
        <td>type</td>
        <td>是</td>
        <td>String</td>
        <td>charge</td>
        <td><a href="#pay4" style="color:#4585d2">支付方式列表</a></td>
      </tr>
      <tr>
        <td>商品名称</td>
        <td>name</td>
        <td>是</td>
        <td>String</td>
        <td>VIP会员</td>
        <td></td>
      </tr>
      <tr>
        <td>商品金额</td>
        <td>money</td>
        <td>是</td>
        <td>String</td>
        <td>100</td>
        <td></td>
      </tr>
      <tr>
        <td>实际支付金额</td>
        <td>realmoney</td>
        <td>是</td>
        <td>String</td>
        <td>100.33</td>
        <td></td>
      </tr>
      <tr>
        <td>支付状态</td>
        <td>trade_status</td>
        <td>是</td>
        <td>String</td>
        <td>TRADE_SUCCESS</td>
        <td>只有TRADE_SUCCESS是成功</td>
      </tr>
      <tr>
        <td>业务扩展参数</td>
        <td>param</td>
        <td>否</td>
        <td>String</td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>签名字符串</td>
        <td>sign</td>
        <td>是</td>
        <td>String</td>
        <td>202cb962ac59075b964b07152d234b70</td>
        <td></td>
      </tr>
      <tr>
        <td>签名类型</td>
        <td>sign_type</td>
        <td>是</td>
        <td>String</td>
        <td>MD5</td>
        <td>默认为MD5</td>
      </tr>
    </tbody>
  </table>
  <p>
    <font color="#993939">收到异步通知后，需返回 success 以表示服务器接收到了订单通知并成功处理，否则将会以一定的时间间隔（15s/15s/30s/3m/10m/20m/30m/30m/30m/60m/3h/3h/3h/6h/6h - 总计 24h4m）继续通知。</font>
  </p>
</div>
<div id="pay2" class="api_block">
  <h3>
    支付结果查询
  </h3>
  <p>
    <font color="#777">此接口可用于查询订单的支付状态。</font>
  </p>
  <p>URL地址：<font color="#29389f">http://payapi.dx888.me/order_status.php</font>
  </p>
  <p>POST</font>
  </p>
  <p>请求参数说明：</p>
  <table class="table table-bordered table-hover">
    <thead>
      <tr>
        <th>字段名</th>
        <th>变量名</th>
        <th>必填</th>
        <th>类型</th>
        <th>示例值</th>
        <th>描述</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>商户ID</td>
        <td>pid</td>
        <td>是</td>
        <td>Int</td>
        <td>1001</td>
        <td></td>
      </tr>
      <tr>
        <td>商户订单号</td>
        <td>out_trade_no</td>
        <td>是</td>
        <td>String</td>
        <td>20160806151343349</td>
        <td></td>
      </tr>
    </tbody>
  </table>
  <p>返回结果（json）：</p>
  <table class="table table-bordered table-hover">
    <thead>
      <tr>
        <th>字段名</th>
        <th>变量名</th>
        <th>类型</th>
        <th>示例值</th>
        <th>描述</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>返回状态码</td>
        <td>code</td>
        <td>Int</td>
        <td>0</td>
        <td>0为成功，其它值为失败</td>
      </tr>
      <tr>
        <td>返回信息</td>
        <td>msg</td>
        <td>String</td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>订单信息</td>
        <td>data</td>
        <td>Array</td>
        <td></td>
        <td>包含字段：<br />pid 商户号<br />trade_no 平台单号<br />out_trade_no 商户单号<br />status 支付状态：SUCCESS（已支付）；NOTPAY（未支付）</td>
      </tr>
    </tbody>
  </table>
</div>
<div id="pay3" class="api_block">
  <h3>
    客户提现接口
  </h3>
  <p>
    <font color="#777">此接口可用于服务器后端发起提现请求</font>
  </p>
  <p>URL地址：<font color="#29389f">http://payapi.dx888.me/withdraw.php</font>
  </p>
  <p>POST</font>
  </p>
  <p>请求参数说明：</p>
  <table class="table table-bordered table-hover">
    <thead>
      <tr>
        <th>字段名</th>
        <th>变量名</th>
        <th>必填</th>
        <th>类型</th>
        <th>示例值</th>
        <th>描述</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>商户ID</td>
        <td>pid</td>
        <td>是</td>
        <td>Int</td>
        <td>1001</td>
        <td></td>
      </tr>
      <tr>
        <td>商户订单号</td>
        <td>out_trade_no</td>
        <td>是</td>
        <td>String</td>
        <td>20160806151343349</td>
        <td>格式：a-zA-Z0-9，长度6-32位</td>
      </tr>
      <tr>
        <td>异步通知地址</td>
        <td>notify_url</td>
        <td>是</td>
        <td>String</td>
        <td>http://www.pay.com/notify_url.php</td>
        <td>服务器异步通知地址，以 http:// 或 https:// 开头</td>
      </tr>
      <tr>
        <td>提现金额</td>
        <td>money</td>
        <td>是</td>
        <td>String</td>
        <td>100</td>
        <td>整型数值，不能有小数点</td>
      </tr>
      <tr>
        <td>银行名称</td>
        <td>bankname</td>
        <td>是</td>
        <td>String</td>
        <td>交通银行</td>
        <td><a href="http://www.culturemark.com/bankcode/bankcode.htm" target="_blank" style="color:green">支持的银行编码</a></td>
      </tr>
      <tr>
        <td>银行账户</td>
        <td>account</td>
        <td>是</td>
        <td>String</td>
        <td>11111111</td>
        <td></td>
      </tr>
      <tr>
        <td>账户名</td>
        <td>username</td>
        <td>是</td>
        <td>String</td>
        <td>小明</td>
        <td></td>
      </tr>
      <tr>
        <td>提现方式</td>
        <td>channel_type</td>
        <td>否</td>
        <td>String</td>
        <td>1</td>
        <td>1-转数快(默认)，2-银行卡</td>
      </tr>
      <tr>
        <td>签名字符串</td>
        <td>sign</td>
        <td>是</td>
        <td>String</td>
        <td>202cb962ac59075b964b07152d234b70</td>
        <td></td>
      </tr>
      <tr>
        <td>签名类型</td>
        <td>sign_type</td>
        <td>是</td>
        <td>String</td>
        <td>MD5</td>
        <td>默认为MD5</td>
      </tr>
    </tbody>
  </table>
  <p>返回结果（json）：</p>
  <table class="table table-bordered table-hover">
    <thead>
      <tr>
        <th>字段名</th>
        <th>变量名</th>
        <th>类型</th>
        <th>示例值</th>
        <th>描述</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>返回状态码</td>
        <td>code</td>
        <td>Int</td>
        <td>0</td>
        <td>0为成功，其它值为失败</td>
      </tr>
      <tr>
        <td>返回信息</td>
        <td>msg</td>
        <td>String</td>
        <td></td>
        <td>成功时返回平台单号，失败时返回原因</td>
      </tr>
    </tbody>
  </table>
</div>
<div id="pay4" class="api_block">
  <h3>
    提现结果通知
  </h3>
  <p>通知类型：服务器异步通知（notify_url）</p>
  <p>请求方式：POST，数据以json的形式放在请求的body中。</p>
  <p>请求参数说明：</p>
  <table class="table table-bordered table-hover">
    <thead>
      <tr>
        <th>字段名</th>
        <th>变量名</th>
        <th>必填</th>
        <th>类型</th>
        <th>示例值</th>
        <th>描述</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>商户ID</td>
        <td>pid</td>
        <td>是</td>
        <td>Int</td>
        <td>1001</td>
        <td></td>
      </tr>
      <tr>
        <td>平台订单号</td>
        <td>trade_no</td>
        <td>是</td>
        <td>String</td>
        <td>20160806151343349021</td>
        <td><?php echo $conf['sitename'] ?>订单号</td>
      </tr>
      <tr>
        <td>商户订单号</td>
        <td>out_trade_no</td>
        <td>是</td>
        <td>String</td>
        <td>20160806151343349</td>
        <td>商户系统内部的订单号</td>
      </tr>
      <tr>
        <td>提现金额</td>
        <td>money</td>
        <td>是</td>
        <td>String</td>
        <td>100</td>
        <td>整型数值，不能有小数点</td>
      </tr>
      <tr>
        <td>银行名称</td>
        <td>bankname</td>
        <td>是</td>
        <td>String</td>
        <td>交通银行</td>
        <td></td>
      </tr>
      <tr>
        <td>银行账户</td>
        <td>account</td>
        <td>是</td>
        <td>String</td>
        <td>11111111</td>
        <td></td>
      </tr>
      <tr>
        <td>账户名</td>
        <td>username</td>
        <td>是</td>
        <td>String</td>
        <td>小明</td>
        <td></td>
      </tr>
      <tr>
        <td>支付状态</td>
        <td>trade_status</td>
        <td>是</td>
        <td>String</td>
        <td>TRADE_SUCCESS</td>
        <td>成功：TRADE_SUCCESS<br />驳回：TRADE_REJECT<br />提现成功后又强制驳回：TRADE_ENFORCE_REJECT<br />提现驳回后又强制完成：TRADE_ENFORCE_SUCCESS</td>
      </tr>
      <tr>
        <td>签名字符串</td>
        <td>sign</td>
        <td>是</td>
        <td>String</td>
        <td>202cb962ac59075b964b07152d234b70</td>
        <td></td>
      </tr>
      <tr>
        <td>签名类型</td>
        <td>sign_type</td>
        <td>是</td>
        <td>String</td>
        <td>MD5</td>
        <td>默认为MD5</td>
      </tr>
    </tbody>
  </table>
  <p>
    <font color="#993939">收到异步通知后，需返回 success 以表示服务器接收到了订单通知并成功处理，否则将会以一定的时间间隔（15s/15s/30s/3m/10m/20m/30m/30m/30m/60m/3h/3h/3h/6h/6h - 总计 24h4m）继续通知。</font>
  </p>
</div>
<div id="pay5" class="api_block">
  <h3>
    提现结果查询
  </h3>
  <p>
    <font color="#777">此接口可用于查询提现订单的支付状态。</font>
  </p>
  <p>URL地址：<font color="#29389f">http://payapi.dx888.me/withdraw_status.php</font>
  </p>
  <p>POST</font>
  </p>
  <p>请求参数说明：</p>
  <table class="table table-bordered table-hover">
    <thead>
      <tr>
        <th>字段名</th>
        <th>变量名</th>
        <th>必填</th>
        <th>类型</th>
        <th>示例值</th>
        <th>描述</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>商户ID</td>
        <td>pid</td>
        <td>是</td>
        <td>Int</td>
        <td>1001</td>
        <td></td>
      </tr>
      <tr>
        <td>商户订单号</td>
        <td>out_trade_no</td>
        <td>是</td>
        <td>String</td>
        <td>20160806151343349</td>
        <td></td>
      </tr>
    </tbody>
  </table>
  <p>返回结果（json）：</p>
  <table class="table table-bordered table-hover">
    <thead>
      <tr>
        <th>字段名</th>
        <th>变量名</th>
        <th>类型</th>
        <th>示例值</th>
        <th>描述</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>返回状态码</td>
        <td>code</td>
        <td>Int</td>
        <td>0</td>
        <td>0为成功，其它值为失败</td>
      </tr>
      <tr>
        <td>返回信息</td>
        <td>msg</td>
        <td>String</td>
        <td></td>
        <td>成功时返回平台单号，失败时返回原因</td>
      </tr>
      <tr>
        <td>订单信息</td>
        <td>data</td>
        <td>Array</td>
        <td></td>
        <td>包含字段：<br />pid 商户号<br />trade_no 平台单号<br />out_trade_no 商户单号<br />status 支付状态：SUCCESS（已支付）；NOTPAY（未支付）；REJECT（驳回）；ENFORCE_REJECT（强制驳回）；ENFORCE_SUCCESS（强制完成）</td>
      </tr>
    </tbody>
  </table>
</div>
<div id="pay6" class="api_block">
  <h3>
    MD5签名算法
  </h3>
  <p>
    请对参数按照键名进行降序排序（a-z），sign和sign_type 和空值不进行签名！。
    排序后请操作参数生成或拼接一个url请求字符串 例如 <code>a=b&amp;c=d&amp;e=f</code> (Url值不能携带参数！不要进行urlencode)
    再将拼接好的请求字符串与平台生成的Key进行MD5加密得出sign签名参数 <code>md5 ( a=b&amp;c=d&amp;e=f + KEY )</code> (注意：+ 为各语言的拼接符！不是字符！)，md5为小写
  </p>
</div>
<div id="pay7" class="api_block">
  <h3>
    支付方式列表
  </h3>
  <table class="table table-bordered table-hover">
    <thead>
      <tr>
        <th>调用值</th>
        <th>显示名称</th>
      </tr>
    </thead>
    <tbody>
      <?php
      foreach ($paytype as $row) {
        echo '<tr><td>' . $row['name'] . '</td><td>' . $row['showname'] . '</td></tr>';
      }
      ?>
    </tbody>
  </table>
</div>